2025-10-20 23:44:15,941 [CRITICAL] Critical error :
Traceback (most recent call last):
  File "d:\TonpalmUnmain\Project\BestDiscordBotEver\main.py", line 602, in <module>
    BANNED_WORDS = load_banned_words("banned")
  File "d:\TonpalmUnmain\Project\BestDiscordBotEver\main.py", line 562, in load_banned_words
    banned = set(data.get("banned_words", []))
                 ^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

